from . import hr_employee
from . import hr_contract
from . import hr_leave_type
from . import hr_leave
from . import hrm_hk_api_key
from . import hrm_hk_webhook
from . import hrm_hk_shift
from . import hr_work_entry_type
from . import hr_work_entry
from . import hr_work_location
from . import hr_attendance
from . import hrm_hk_notification
from . import hrm_hk_notice
from . import hrm_hk_holiday_lieu
from . import hrm_hk_push
from . import hr_payslip
from . import hrm_hk_ess_request
